"""add user

Revision ID: 4cae1a24f017
Revises: 5a65443fa855
Create Date: 2025-03-20 16:36:42.861316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cae1a24f017'
down_revision: Union[str, None] = '5a65443fa855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_phone_key', 'contacts', type_='unique')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=True)
    op.create_unique_constraint('contacts_phone_key', 'contacts', ['phone'])
    # ### end Alembic commands ###
